--- # Playbook - 01 - Install elinks on webserver
- hosts: web
  vars:
    control_server: localhost
    web_root: /var/www/html
  tasks:
  - name: Install elinks 
    yum: pkg=elinks state=latest
...
