---
- name: Create Logstash Repo
  shell: echo -e "[logstash]\nname=Logstash\nbaseurl=http://packages.elasticsearch.org/logstash/2.2/centos\ngpgcheck=1\ngpgkey=http://packages.elasticsearch.org/GPG-KEY-elasticsearch\nenabled=1" > /etc/yum.repos.d/logstash.repo
- name: Install logstash
  yum: name=logstash state=latest
- name: Creating certs directories for SSL
  file: path=/etc/pki/tls/certs state=directory
- name: Generate SSL certificates
  shell: "openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"
- name: Configure Beats configuration file
  template: src=beats-input.conf.j2 dest=/etc/logstash/conf.d/02-beats-input.conf owner=root group=root mode=0644
- name: Configure Syslog Filter
  template: src=syslog-filter.conf.j2 dest=/etc/logstash/conf.d/10-syslog-filter.conf owner=root group=root mode=0644
- name: Configure Elasticsearch output file
  template: src=elasticsearch-output.conf.j2 dest=/etc/logstash/conf.d/30-elasticsearch-output.conf owner=root group=root mode=0644
  notify: Restart Logstash
