--- # Web Playbook
- hosts: web
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_files:
  - variables/variables.yml
  tasks:
  - include: packages/packages.yml
  - include: commands/commands.yml
  - include: handlers/handlers.yml
...
