--- # Playbook demo of debug and register statement
- hosts: web1
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Telnet
    yum:
      name: telnet
      state: latest
    register: result
  - debug: var=result  
